### ISSUE TITLE
Iteratively compute set coefficients according to Gray code sequence

### ISSUE THREAD

**Issue by cargodog** [cargodog/arcturus#19]
### Overview
Currently, each member of the set is multiplied by a coefficient, computed as a polynomial combination of each proof input's `f_ji` tensor. For an `m` digit proof configuration, this requires `m` scalar multiplications per member in the set for each proof being verified. So, if we are verifying `p` proofs, each with `u` inputs, with a set size of `N = n^m`, this requires `p * u * m * N` multiplications in total, just to compute the set coefficients.

If instead we use Gray coded indices (each subsequent index differs from the previous index by only one digit), we can leverage this to iteratively compute each coefficient efficiently from the previous coefficient. To illustrate this, consider the following examples over a 3 bit set.

> `j = [0..n)` and `i = [0..m)`

> Example: `f_01` refers to the `j = 0` & `i = 1` position in the `f_ji` tensor

> Each proof will have a different number of inputs, so `u` will not be constant across proofs, but I assume constant `u` for simplicity.

### Current approach (`m = 3`, `n = 2`)
`m` multiplications for each `k`
| k (dec) | k (binary) | coeff_k |
|:-------|:--------|:------------|
| 0 | 000 | f02 * f01 * f00 | 
| 1 | 001 | f02 * f01 * f10 | 
| 2 | 010 | f02 * f11 * f00 | 
| 3 | 011 | f02 * f11 * f10 | 
| 4 | 100 | f12 * f01 * f00 | 
| 5 | 101 | f12 * f01 * f10 | 
| 6 | 110 | f12 * f11 * f00 | 
| 7 | 111 | f12 * f11 * f10 |

### Optimized approach (`m = 3`, `n = 2`)
`2` multiplications and one inversion for each `k`
| k (dec) | k (Gray) | coeff_k (optimized) |
|:-------|:-----------|:------------------------|
| 0 | 000 | f02 * f01 * f00 |
| 1 | 001 | coeff_0 * f10 / f00 |
| 2 | 011 | coeff_1 * f11 / f01 |
| 3 | 010 | coeff_2 * f00 / f10 |
| 4 | 110 | coeff_3 * f12 / f02 |
| 5 | 111 | coeff_4 * f10 / f00 |
| 6 | 101 | coeff_5 * f01 / f11 |
| 7 | 100 | coeff_6 * f00 / f10 |

### Summary
Gray coded indices allow saving apprx. `p * u * m/2` multiplications in a batch verification of `p` proofs, with `u` inputs each.

**Comment by SarangNoether** [comment]
It may be worth noting that the scalar inversion process involves a fixed number of squarings and multiplications per inverse using an optimized addition chain. It's likely that for low enough `N` this may not provide much benefit at all, if any.

Edit: I neglected to account for batch scalar inversion, which means only a single inversion is needed for this process!

**Comment by cargodog** [comment]
> It may be worth noting that the scalar inversion process involves a fixed number of squarings and multiplications per inverse using an optimized addition chain. It's likely that for low enough `N` this may not provide much benefit at all, if any.
> 
> Edit: I neglected to account for batch scalar inversion, which means only a single inversion is needed for this process!

Indeed. The inversion cost is quite cheap :)

Once I have formalized the `n`-ary Gray code construction for One-out-of-Many proofs, I will work to implement it here in Arcturus. Preliminary tinkering has me very optimistic.

**Comment by cargodog** [comment]
From IRC, sarang has suggested an example of extended "'n'-ary" Gray codes:
```# Extended Gray codes
# base N, length K
def gray(N,K):
    g = [0 for _ in range(K+1)]
    u = [1 for _ in range(K+1)]

    for idx in range(9): # max N**K
        print(idx,''.join(reversed([str(i) for i in g[:-1]])))
        i = 0
        k = g[0] + u[0]
        while (k >= N or k < 0):
            u[i] = -u[i]
            i += 1
            k = g[i] + u[i]
        g[i] = k

gray(3,3)
```

**Comment by SarangNoether** [comment]
Here is Python code for [Arcturus](https://github.com/SarangNoether/skunkworks/tree/arcturus) that shows how to do this, and for the related [Triptych](https://github.com/SarangNoether/skunkworks/tree/triptych) proving system. Neither uses batch inversion yet, but this is straightforward.

**Comment by cargodog** [comment]
As mentioned in https://github.com/cargodog/arcturus/pull/35, this issue is no longer a priority, as recursive polynomial evaluation offers even greater efficiency than the proposed Gray coded approach. Inspired by the Beam developers' work optimizing Lelantus. See here: https://forum.firo.org/t/gray-code-optimization-for-lelantus/930/10
